name: Increment Package Version

on:
  push:
    branches: [dev]  

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Increment version
        run: npm version patch --no-git-tag-version
 
      - name: Commit version change
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH_NAME: 'dev'
